server:
  port: 8089
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gisdb
    username: postgres
    password: yourpassword
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
    show-sql: true
